### ISSUE TITLE
Semantic Segmentation vs Instance Segmentation

### ISSUE THREAD

**Issue by Skylixia** [JanusSyrak/ConeSLAM#1]
Hi, 

Thanks for sharing this repo! 
I wanted to ask what was the reasoning behind choosing semantic segmentation over instance segmentation ? I would think that to be able to do an accurate mapping with SLAM, it would be better to have an instance segmentation of the cones so the cones are individualized even when overlapped and can each have their own depth estimation etc. Is the centerestimation script to individualize the cones of the semantic mask using the LIDAR for SLAM to be able compute the mapping then ? If yes, why not have instance segmentation directly ?

Thanks in advance!

**Comment by JanusSyrak** [comment]
No problem! We were using a very accurate LiDAR for 3D localization of the cones, and so we only needed to know the color of each of the 3D points. There was no need for us to know the specific cone a point belonged to, only a color. The center estimation script computes the center of each of the previously found cones.

**Comment by Skylixia** [comment]
Thanks for your reply ! Thus, the center estimation is not the center of a single cone extracted from a cluster (semantic mask) ?

**Comment by JanusSyrak** [comment]
The center estimation estimates the center of a single cone, represented as a cluster of 3D points. The clustering has nothing to do with the image segmentation. The image segmentation is purely performed in order to determine the color of the cone this specific cluster represents.

**Comment by JanusSyrak** [comment]
I added our thesis as a file in the repository, which contains a better explanation for our choices than what I can hope to provide in a Q&A format.

**Comment by Skylixia** [comment]
Thats awesome thank you !
